version: '3.1'

services:
  app:
    image: photo-header:latest
    # image: johnmastro/photo-header:latest
    environment:
      PORT: 3000
      MONGO_HOST: 52.53.188.2
      # MONGO_HOST: localhost
      MONGO_USER: root
      MONGO_PORT: 27017
      MONGO_PSWD_FILE: /run/secrets/mongo-password
    ports:
      - "3000:3000"
    secrets:
      - mongo-password

secrets:
  mongo-password:
    file: ./mongo-password
