version: '3.1'
services:
  app:
    image: photo-header:latest
    depends_on:
      - db
    links:
      - db
    environment:
      PORT: 3000
      PGHOST: db
      PGUSER: yelp
      PGPASSWORD: yelp
    ports:
      - "3000:3000"
#   proxy:
#     image: whelp-proxy
#     ports:
#       - 80:2000
  db:
    image: photo-header-db:latest
    # volumes:
    #   - /var/lib/postgresql/data
    environment:
      POSTGRES_USER: yelp
      POSTGRES_DB: yelp
      POSTGRES_PASSWORD: yelp
    ports:
      - "5432:5432"
