drop database if exists yelp;

create database yelp;

create table users {
    id int generated by default as identity primary key,
    name varchar(50) not null
};

create table restaurants {
    id int generated by default as identity primary key,
    address varchar(250) not null,
    phone_number varchar(50) not null,
    url varchar(250) not null,
    google_map varchar(2500) not null,
    categories varchar(50) not null
};

create table photos {
    id int generated by default as identity primary key,
    url varchar(250),
    comment varchar(50),
    user_id int references users(id),
    restaurant_id int references restaurants(id)
};

create table users_restaurants {
    user_id references users(id),
    restaurant_id int references users(id),
    primary key (user_id, restaurant_id)
};
