FROM postgres:9.3
ENV POSTGRES_USER Kevin
ENV POSTGRES_PASSWORD docker
ENV POSTGRES_DB yelp
RUN apt-get update && apt-get install -y postgresql-9.3 postgresql-client-9.3 postgresql-contrib-9.3

EXPOSE 5432
